import telebot
from telebot.types import InlineKeyboardButton, InlineKeyboardMarkup, ReplyKeyboardMarkup, KeyboardButton
import config
bot = telebot.TeleBot(config.token)
player1 = 'Clown'
player2 = 'Witcher'
#def keyboard_buttons():
    #markup = ReplyKeyboardMarkup()
    #button1 = KeyboardButton('Create ur own')
    #button2 = KeyboardButton('Buy our')
    #markup.add(button1, button2)
    #return markup
def inline_buttons_stone():
    markup = InlineKeyboardMarkup()
    btn1 = InlineKeyboardButton('Turn left', callback_data='Stone left')
    btn2 = InlineKeyboardButton('Turn right', callback_data='Stone right')
    markup.add(btn1, btn2)
    return markup
def inline_buttons_sage():
    markup = InlineKeyboardMarkup()
    btn1 = InlineKeyboardButton('Enter a dungeon', callback_data='Dungeon')
    btn2 = InlineKeyboardButton('Go to the forest', callback_data='Forest')
    markup.add(btn1, btn2)
    return markup
@bot.message_handler(commands=['start'])
def send_welcome(message):
    if message.text:
        #bot.send_message(message.chat.id, f'Glad to see you, {message.from_user.first_name} \nWelcome to COMPX.UA, where u can create ur own pc, or buy that we already have', reply_markup=keyboard_buttons())
        bot.send_message(message.chat.id, f"{player1} and {player2} were walking through the forest and met a stone. There was a message on it:", reply_markup=inline_buttons_stone())
@bot.callback_query_handler(func=lambda call: True)
def callback_query(call):
    if call.data == 'Stone left':
        bot.send_message(call.from_user.id, 'Congratulation, U died')
    if call.data == 'Stone right':
        bot.send_message(call.from_user.id, 'U reached Sage')
        bot.send_photo(call.from_user.id, 'https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8a627ec10b57f4f2/5eb7cdc16509f3370a5a93b7/V_AGENTS_587x900_sage.png')
        bot.send_message(call.from_user.id, f'{player1} and {player2} met a Sage and he told them:', reply_markup=inline_buttons_sage())
    if call.data == 'Dungeon':
        bot.send_message(call.from_user.id, 'U was killed by a Skeleton')
    if call.data == 'Forest':
        bot.send_message(call.from_user.id, 'U left the cursed forest and WON THIS GAME!!!')
        bot.send_photo(call.from_user.id, 'https://static.vecteezy.com/system/resources/previews/010/976/287/original/golden-cup-3d-red-ribbon-winner-1st-place-minimal-gold-winners-stars-on-podium-champion-award-ceremony-concept-in-cartoon-style-trophy-render-isolated-on-white-background-game-or-education-free-vector.jpg')
        bot.send_audio(call.from_user.id, open('LOVV66, SEEMEE - Новая эра.mp3', 'rb'))
#@bot.message_handler(content_types=['text'])
#def conversation(message):
    #if message.text == 'Buy our':
        #bot.send_message(message.chat.id, 'Look that we have for u')
        #bot.send_photo(message.chat.id, open('Lil Chill.jpeg', 'rb'))
    #if message.text == 'None':
        #bot.send_message(message.chat.id, 'Create ur own')
bot.polling(none_stop=True)


#{'content_type': 'text', 'id': 271, 'message_id': 271, 'from_user': {'id': 984062143, 'is_bot': False, 'first_name': 'solom_kkka', 'username': 'solom_kkka', 'last_name': None, 'language_code': 'ru', 'can_join_groups': None, 'can_read_all_group_messages': None, 'supports_inline_queries': None, 'is_premium': None, 'added_to_attachment_menu': None}, 'date': 1676139902, 'chat': {'id': 984062143, 'type': 'private', 'title': None, 'username': 'solom_kkka', 'first_name': 'solom_kkka', 'last_name': None, 'is_forum': None, 'photo': None, 'bio': None, 'join_to_send_messages': None, 'join_by_request': None, 'has_private_forwards': None, 'has_restricted_voice_and_video_messages': None, 'description': None, 'invite_link': None, 'pinned_message': None, 'permissions': None, 'slow_mode_delay': None, 'message_auto_delete_time': None, 'has_protected_content': None, 'sticker_set_name': None, 'can_set_sticker_set': None, 'linked_chat_id': None, 'location': None, 'active_usernames': None, 'emoji_status_custom_emoji_id': None, 'has_hidden_members': None, 'has_aggressive_anti_spam_enabled': None}, 'sender_chat': None, 'forward_from': None, 'forward_from_chat': None, 'forward_from_message_id': None, 'forward_signature': None, 'forward_sender_name': None, 'forward_date': None, 'is_automatic_forward': None, 'reply_to_message': None, 'via_bot': None, 'edit_date': None, 'has_protected_content': None, 'media_group_id': None, 'author_signature': None, 'text': '/start', 'entities': [<telebot.types.MessageEntity object at 0x0000029FED197650>], 'caption_entities': None, 'audio': None, 'document': None, 'photo': None, 'sticker': None, 'video': None, 'video_note': None, 'voice': None, 'caption': None, 'contact': None, 'location': None, 'venue': None, 'animation': None, 'dice': None, 'new_chat_member': None, 'new_chat_members': None, 'left_chat_member': None, 'new_chat_title': None, 'new_chat_photo': None, 'delete_chat_photo': None, 'group_chat_created': None, 'supergroup_chat_created': None, 'channel_chat_created': None, 'migrate_to_chat_id': None, 'migrate_from_chat_id': None, 'pinned_message': None, 'invoice': None, 'successful_payment': None, 'connected_website': None, 'reply_markup': None, 'message_thread_id': None, 'is_topic_message': None, 'forum_topic_created': None, 'forum_topic_closed': None, 'forum_topic_reopened': None, 'has_media_spoiler': None, 'forum_topic_edited': None, 'general_forum_topic_hidden': None, 'general_forum_topic_unhidden': None, 'write_access_allowed': None, 'json': {'message_id': 271, 'from': {'id': 984062143, 'is_bot': False, 'first_name': 'solom_kkka', 'username': 'solom_kkka', 'language_code': 'ru'}, 'chat': {'id': 984062143, 'first_name': 'solom_kkka', 'username': 'solom_kkka', 'type': 'private'}, 'date': 1676139902, 'text': '/start', 'entities': [{'offset': 0, 'length': 6, 'type': 'bot_command'}]}}
#{'content_type': 'text', 'id': 273, 'message_id': 273, 'from_user': {'id': 672519922, 'is_bot': False, 'first_name': 'Flora🌺', 'username': 'SalineKing', 'last_name': None, 'language_code': 'ru', 'can_join_groups': None, 'can_read_all_group_messages': None, 'supports_inline_queries': None, 'is_premium': None, 'added_to_attachment_menu': None}, 'date': 1676140146, 'chat': {'id': 672519922, 'type': 'private', 'title': None, 'username': 'SalineKing', 'first_name': 'Flora🌺', 'last_name': None, 'is_forum': None, 'photo': None, 'bio': None, 'join_to_send_messages': None, 'join_by_request': None, 'has_private_forwards': None, 'has_restricted_voice_and_video_messages': None, 'description': None, 'invite_link': None, 'pinned_message': None, 'permissions': None, 'slow_mode_delay': None, 'message_auto_delete_time': None, 'has_protected_content': None, 'sticker_set_name': None, 'can_set_sticker_set': None, 'linked_chat_id': None, 'location': None, 'active_usernames': None, 'emoji_status_custom_emoji_id': None, 'has_hidden_members': None, 'has_aggressive_anti_spam_enabled': None}, 'sender_chat': None, 'forward_from': None, 'forward_from_chat': None, 'forward_from_message_id': None, 'forward_signature': None, 'forward_sender_name': None, 'forward_date': None, 'is_automatic_forward': None, 'reply_to_message': None, 'via_bot': None, 'edit_date': None, 'has_protected_content': None, 'media_group_id': None, 'author_signature': None, 'text': '/start', 'entities': [<telebot.types.MessageEntity object at 0x0000029FED46F010>], 'caption_entities': None, 'audio': None, 'document': None, 'photo': None, 'sticker': None, 'video': None, 'video_note': None, 'voice': None, 'caption': None, 'contact': None, 'location': None, 'venue': None, 'animation': None, 'dice': None, 'new_chat_member': None, 'new_chat_members': None, 'left_chat_member': None, 'new_chat_title': None, 'new_chat_photo': None, 'delete_chat_photo': None, 'group_chat_created': None, 'supergroup_chat_created': None, 'channel_chat_created': None, 'migrate_to_chat_id': None, 'migrate_from_chat_id': None, 'pinned_message': None, 'invoice': None, 'successful_payment': None, 'connected_website': None, 'reply_markup': None, 'message_thread_id': None, 'is_topic_message': None, 'forum_topic_created': None, 'forum_topic_closed': None, 'forum_topic_reopened': None, 'has_media_spoiler': None, 'forum_topic_edited': None, 'general_forum_topic_hidden': None, 'general_forum_topic_unhidden': None, 'write_access_allowed': None, 'json': {'message_id': 273, 'from': {'id': 672519922, 'is_bot': False, 'first_name': 'Flora🌺', 'username': 'SalineKing', 'language_code': 'ru'}, 'chat': {'id': 672519922, 'first_name': 'Flora🌺', 'username': 'SalineKing', 'type': 'private'}, 'date': 1676140146, 'text': '/start', 'entities': [{'offset': 0, 'length': 6, 'type': 'bot_command'}]}}
#{'content_type': 'text', 'id': 275, 'message_id': 275, 'from_user': {'id': 1672386126, 'is_bot': False, 'first_name': 'HELIOS×bloom', 'username': 'elis_fom', 'last_name': None, 'language_code': 'ru', 'can_join_groups': None, 'can_read_all_group_messages': None, 'supports_inline_queries': None, 'is_premium': None, 'added_to_attachment_menu': None}, 'date': 1676140185, 'chat': {'id': 1672386126, 'type': 'private', 'title': None, 'username': 'elis_fom', 'first_name': 'HELIOS×bloom', 'last_name': None, 'is_forum': None, 'photo': None, 'bio': None, 'join_to_send_messages': None, 'join_by_request': None, 'has_private_forwards': None, 'has_restricted_voice_and_video_messages': None, 'description': None, 'invite_link': None, 'pinned_message': None, 'permissions': None, 'slow_mode_delay': None, 'message_auto_delete_time': None, 'has_protected_content': None, 'sticker_set_name': None, 'can_set_sticker_set': None, 'linked_chat_id': None, 'location': None, 'active_usernames': None, 'emoji_status_custom_emoji_id': None, 'has_hidden_members': None, 'has_aggressive_anti_spam_enabled': None}, 'sender_chat': None, 'forward_from': None, 'forward_from_chat': None, 'forward_from_message_id': None, 'forward_signature': None, 'forward_sender_name': None, 'forward_date': None, 'is_automatic_forward': None, 'reply_to_message': None, 'via_bot': None, 'edit_date': None, 'has_protected_content': None, 'media_group_id': None, 'author_signature': None, 'text': '/start', 'entities': [<telebot.types.MessageEntity object at 0x0000029FED46E950>], 'caption_entities': None, 'audio': None, 'document': None, 'photo': None, 'sticker': None, 'video': None, 'video_note': None, 'voice': None, 'caption': None, 'contact': None, 'location': None, 'venue': None, 'animation': None, 'dice': None, 'new_chat_member': None, 'new_chat_members': None, 'left_chat_member': None, 'new_chat_title': None, 'new_chat_photo': None, 'delete_chat_photo': None, 'group_chat_created': None, 'supergroup_chat_created': None, 'channel_chat_created': None, 'migrate_to_chat_id': None, 'migrate_from_chat_id': None, 'pinned_message': None, 'invoice': None, 'successful_payment': None, 'connected_website': None, 'reply_markup': None, 'message_thread_id': None, 'is_topic_message': None, 'forum_topic_created': None, 'forum_topic_closed': None, 'forum_topic_reopened': None, 'has_media_spoiler': None, 'forum_topic_edited': None, 'general_forum_topic_hidden': None, 'general_forum_topic_unhidden': None, 'write_access_allowed': None, 'json': {'message_id': 275, 'from': {'id': 1672386126, 'is_bot': False, 'first_name': 'HELIOS×bloom', 'username': 'elis_fom', 'language_code': 'ru'}, 'chat': {'id': 1672386126, 'first_name': 'HELIOS×bloom', 'username': 'elis_fom', 'type': 'private'}, 'date': 1676140185, 'text': '/start', 'entities': [{'offset': 0, 'length': 6, 'type': 'bot_command'}]}}
#{'content_type': 'text', 'id': 286, 'message_id': 286, 'from_user': {'id': 1759641152, 'is_bot': False, 'first_name': 'dsweex', 'username': 'swagwxx', 'last_name': None, 'language_code': 'ru', 'can_join_groups': None, 'can_read_all_group_messages': None, 'supports_inline_queries': None, 'is_premium': None, 'added_to_attachment_menu': None}, 'date': 1676236621, 'chat': {'id': 1759641152, 'type': 'private', 'title': None, 'username': 'swagwxx', 'first_name': 'dsweex', 'last_name': None, 'is_forum': None, 'photo': None, 'bio': None, 'join_to_send_messages': None, 'join_by_request': None, 'has_private_forwards': None, 'has_restricted_voice_and_video_messages': None, 'description': None, 'invite_link': None, 'pinned_message': None, 'permissions': None, 'slow_mode_delay': None, 'message_auto_delete_time': None, 'has_protected_content': None, 'sticker_set_name': None, 'can_set_sticker_set': None, 'linked_chat_id': None, 'location': None, 'active_usernames': None, 'emoji_status_custom_emoji_id': None, 'has_hidden_members': None, 'has_aggressive_anti_spam_enabled': None}, 'sender_chat': None, 'forward_from': None, 'forward_from_chat': None, 'forward_from_message_id': None, 'forward_signature': None, 'forward_sender_name': None, 'forward_date': None, 'is_automatic_forward': None, 'reply_to_message': None, 'via_bot': None, 'edit_date': None, 'has_protected_content': None, 'media_group_id': None, 'author_signature': None, 'text': '/start', 'entities': [<telebot.types.MessageEntity object at 0x0000024414DCEFD0>], 'caption_entities': None, 'audio': None, 'document': None, 'photo': None, 'sticker': None, 'video': None, 'video_note': None, 'voice': None, 'caption': None, 'contact': None, 'location': None, 'venue': None, 'animation': None, 'dice': None, 'new_chat_member': None, 'new_chat_members': None, 'left_chat_member': None, 'new_chat_title': None, 'new_chat_photo': None, 'delete_chat_photo': None, 'group_chat_created': None, 'supergroup_chat_created': None, 'channel_chat_created': None, 'migrate_to_chat_id': None, 'migrate_from_chat_id': None, 'pinned_message': None, 'invoice': None, 'successful_payment': None, 'connected_website': None, 'reply_markup': None, 'message_thread_id': None, 'is_topic_message': None, 'forum_topic_created': None, 'forum_topic_closed': None, 'forum_topic_reopened': None, 'has_media_spoiler': None, 'forum_topic_edited': None, 'general_forum_topic_hidden': None, 'general_forum_topic_unhidden': None, 'write_access_allowed': None, 'json': {'message_id': 286, 'from': {'id': 1759641152, 'is_bot': False, 'first_name': 'dsweex', 'username': 'swagwxx', 'language_code': 'ru'}, 'chat': {'id': 1759641152, 'first_name': 'dsweex', 'username': 'swagwxx', 'type': 'private'}, 'date': 1676236621, 'text': '/start', 'entities': [{'offset': 0, 'length': 6, 'type': 'bot_command'}]}}
#{'content_type': 'text', 'id': 294, 'message_id': 294, 'from_user': {'id': 987950014, 'is_bot': False, 'first_name': 'поліна', 'username': 'polianaspm', 'last_name': None, 'language_code': 'uk', 'can_join_groups': None, 'can_read_all_group_messages': None, 'supports_inline_queries': None, 'is_premium': None, 'added_to_attachment_menu': None}, 'date': 1676236637, 'chat': {'id': 987950014, 'type': 'private', 'title': None, 'username': 'polianaspm', 'first_name': 'поліна', 'last_name': None, 'is_forum': None, 'photo': None, 'bio': None, 'join_to_send_messages': None, 'join_by_request': None, 'has_private_forwards': None, 'has_restricted_voice_and_video_messages': None, 'description': None, 'invite_link': None, 'pinned_message': None, 'permissions': None, 'slow_mode_delay': None, 'message_auto_delete_time': None, 'has_protected_content': None, 'sticker_set_name': None, 'can_set_sticker_set': None, 'linked_chat_id': None, 'location': None, 'active_usernames': None, 'emoji_status_custom_emoji_id': None, 'has_hidden_members': None, 'has_aggressive_anti_spam_enabled': None}, 'sender_chat': None, 'forward_from': None, 'forward_from_chat': None, 'forward_from_message_id': None, 'forward_signature': None, 'forward_sender_name': None, 'forward_date': None, 'is_automatic_forward': None, 'reply_to_message': None, 'via_bot': None, 'edit_date': None, 'has_protected_content': None, 'media_group_id': None, 'author_signature': None, 'text': '/start', 'entities': [<telebot.types.MessageEntity object at 0x0000024414DCF150>], 'caption_entities': None, 'audio': None, 'document': None, 'photo': None, 'sticker': None, 'video': None, 'video_note': None, 'voice': None, 'caption': None, 'contact': None, 'location': None, 'venue': None, 'animation': None, 'dice': None, 'new_chat_member': None, 'new_chat_members': None, 'left_chat_member': None, 'new_chat_title': None, 'new_chat_photo': None, 'delete_chat_photo': None, 'group_chat_created': None, 'supergroup_chat_created': None, 'channel_chat_created': None, 'migrate_to_chat_id': None, 'migrate_from_chat_id': None, 'pinned_message': None, 'invoice': None, 'successful_payment': None, 'connected_website': None, 'reply_markup': None, 'message_thread_id': None, 'is_topic_message': None, 'forum_topic_created': None, 'forum_topic_closed': None, 'forum_topic_reopened': None, 'has_media_spoiler': None, 'forum_topic_edited': None, 'general_forum_topic_hidden': None, 'general_forum_topic_unhidden': None, 'write_access_allowed': None, 'json': {'message_id': 294, 'from': {'id': 987950014, 'is_bot': False, 'first_name': 'поліна', 'username': 'polianaspm', 'language_code': 'uk'}, 'chat': {'id': 987950014, 'first_name': 'поліна', 'username': 'polianaspm', 'type': 'private'}, 'date': 1676236637, 'text': '/start', 'entities': [{'offset': 0, 'length': 6, 'type': 'bot_command'}]}}
